pipeline:
  build-dev:
    image: plugins/docker
    repo: schvpn/website
    secrets: [ docker_username, docker_password ]
    tag: [ dev ]
    when:
      branch: dev

  build-prod:
    image: plugins/docker
    repo: schvpn/website
    secrets: [ docker_username, docker_password ]
    tag: [ master ]
    when:
      branch: master

  rancher:
    image: peloton/drone-rancher
    url: ${RANCHER_URL}
    access_key: ${RANCHER_ACCESS_KEY}
    secret_key: ${RANCHER_SECRET_KEY}
    service: schoolvpn/website
    docker_image: schvpn/website
    confirm: true
    when:
      branch: master