kind: pipeline
name: default

steps:
- name: build-dev  
  image: plugins/docker
  settings:
    repo: schvpn/website
    username:
      from_secret: docker_username
    password:
      from_secret: docker_password
    tag: dev
  when:
      branch: dev

- name: build-prod  
  image: plugins/docker
  settings:
    repo: schvpn/website
    username:
      from_secret: docker_username
    password:
      from_secret: docker_password
    tag: latest
  when:
      branch: master